### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by missemily2022** [sayeed205/Heroku-Switcher#1]
I would like to know how does this work?
Moreover without our Heroku Emails how can it switch apps with just the API Keys?

It would help if these things are mentioned in the Readme.

Btw Love your App :)

**Comment by sayeed205** [comment]
It transfers your app to second account on 15th day and to main acc on 1st day of a month.

**Comment by missemily2022** [comment]
@sayeed205 I know that 
But how with just the API Key?
Every other applications asks for both the API Key and the Associated Heroku Email.

**Comment by sayeed205** [comment]
> @sayeed205 I know that But how with just the API Key? Every other applications asks for both the API Key and the Associated Heroku Email.

You are providing API key means you are providing everything related to your account.
Check [this line](https://github.com/sayeed205/Heroku-Switcher/blob/983aba0b960d138d906708eb04b6479c5477e30d/backend/heroku.js#L43) here getting info about account and [here](https://github.com/sayeed205/Heroku-Switcher/blob/983aba0b960d138d906708eb04b6479c5477e30d/backend/heroku.js#L113) getting the email.

I hope you understood.

**Comment by carolynsteeves1** [comment]
sayeed missemily is known for copying repos and labeling as her own.

**Comment by sayeed205** [comment]
> sayeed missemily is known for copying repos and labeling as her own.

I know very well maybe check [this original maybe](https://github.com/tiararosebiezetta/HerokuDynoSwitcher) and [this copy maybe](https://github.com/missemily2022/DynoChanger)
