### ISSUE TITLE
Suggestion for Readme

### ISSUE THREAD

**Issue by vishnoe115** [sayeed205/Heroku-Switcher#2]
Bro, does this deployable in cloudflare pages? at least give short installation guide  in Readme,, seems nice work, thank you. you've been doing great.

**Comment by sayeed205** [comment]
> Bro, does this deployable in cloudflare pages? at least give short installation guide in Readme,, seems nice work, thank you. you've been doing great.

I dunno much about CF so dunno if it possible to deploy in CF. And for installation guide, will add later when I get time. I really sucks at writing documentations.

**Comment by carolynsteeves1** [comment]
is it possible to deploy in github pages?

**Comment by sayeed205** [comment]
> is it possible to deploy in github pages?

Not sure 
I dunno much about github pages. And I guess github pages only renders static pages but Heroku Switcher need backend too.
