### ISSUE TITLE
What is all this?

### ISSUE THREAD

**Issue by carolynsteeves1** [sayeed205/Heroku-Switcher#4]
MONGO_URI= #your mongoDB uri
JWT_SECRET= #your jwt secret to auth user can be anything
DB_NAME= #your mongoDB name
COLLECTION_NAME= #your mongoDB collection name
NODE_ENV=productio

- i wanna deploy on my vps, but idk where to get these from. Can you make more detailed readme?

**Comment by salman0ansari** [comment]
MONGO_URI= `get this from` [here](https://www.mongodb.com/cloud/atlas/register)
JWT_SECRET= `random string`
DB_NAME= `MongoDB Database name get it from Atlas`
COLLECTION_NAME= `Database Collection name learn more about it` [here](https://www.mongodb.com/docs/manual/core/databases-and-collections/)
NODE_ENV=`production`

**Comment by sayeed205** [comment]
> MONGO_URI= `get this from` [here](https://www.mongodb.com/cloud/atlas/register) JWT_SECRET= `random string` DB_NAME= `MongoDB Database name get it from Atlas` COLLECTION_NAME= `Database Collection name learn more about it` [here](https://www.mongodb.com/docs/manual/core/databases-and-collections/) NODE_ENV=`production`

Thank you
